version: '3'
services:
  programer-notes:
    build: .
    ports:
    - 4000:4000
    volumes:
    - "/home/tangjizhou/programer-notes:/gitbook"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: always
